name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: vanityurl
    attributes:
      label: C3 Vanity URL
      description: Please enter the relevant C3 vanity url. 
      placeholder: https://mytag-mytenant.c3dti.ai
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: resources
    attributes:
      label: C3 Resources
      description: Select one or more c3 resources that are affected.
      options:
        - C3 Static Console
        - C3 Jupyter
        - C3 Ex Machina
        - C3 Developer Portal
        - C3 Okta Authentication
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  
