name: C3 Problem Report
description: File a report for problem encountered useing C3 DTI resources.
title: "[C3 Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this problem report!
  - type: input
    id: vanityurl
    attributes:
      label: C3 Vanity URL
      description: Please enter the relevant C3 vanity url. 
      placeholder: https://mytag-mytenant.c3dti.ai
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: 'Provide details on what is happening and what did you expect to happen?  
      This field supports drag-n-drop of images.  
      Please provide as much detail as possible.' 
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: resources
    attributes:
      label: C3 Resources
      description: Select one or more c3 resources that are affected.
      options:
        - label: C3 Static Console
        - label: C3 Jupyter
        - label: C3 Ex Machina
        - label: C3 Developer Portal
        - label: C3 Okta Authentication
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  
